#ifndef CONSTANTS_H
#define CONSTANTS_H

enum {
	STRING_INDEX_ZERO = 0,
	STRING_INDEX_MANUFACTURER,
	STRING_INDEX_PRODUCT,
	STRING_INDEX_CONFIG1,
	STRING_INDEX_CONFIG2,
	STRING_INDEX_CONFIG3,
	STRING_INDEX_CONFIG4,
	STRING_INDEX_CONFIG5,
	STRING_INDEX_CONFIG6,
	STRING_INDEX_SERIAL,
};

#endif

