#ifndef CONSTANTS_H
#define CONSTANTS_H

/**
 * \brief The string indices understood by a GET DESCRIPTOR(String) request.
 */
enum {
	STRING_INDEX_ZERO = 0,
	STRING_INDEX_MANUFACTURER,
	STRING_INDEX_PRODUCT,
	STRING_INDEX_CONFIG1,
	STRING_INDEX_CONFIG2,
	STRING_INDEX_CONFIG3,
	STRING_INDEX_CONFIG4,
	STRING_INDEX_CONFIG5,
	STRING_INDEX_CONFIG6,
	STRING_INDEX_SERIAL,
};

/**
 * \brief The vendor-specific control requests understood by the dongle.
 */
enum {
	CONTROL_REQUEST_GET_CHANNEL = 0,
	CONTROL_REQUEST_SET_CHANNEL,
	CONTROL_REQUEST_GET_SYMBOL_RATE,
	CONTROL_REQUEST_SET_SYMBOL_RATE,
	CONTROL_REQUEST_GET_PAN_ID,
	CONTROL_REQUEST_SET_PAN_ID,
	CONTROL_REQUEST_GET_MAC_ADDRESS,
	CONTROL_REQUEST_SET_MAC_ADDRESS,
	CONTROL_REQUEST_GET_ADDRESS_MAP_ENTRY,
	CONTROL_REQUEST_SET_ADDRESS_MAP_ENTRY,
	CONTROL_REQUEST_GET_PROMISCUOUS_FLAGS,
	CONTROL_REQUEST_SET_PROMISCUOUS_FLAGS,
	CONTROL_REQUEST_GET_CONTROL_LINES,
	CONTROL_REQUEST_SET_CONTROL_LINES,
	CONTROL_REQUEST_GET_SHORT_REGISTER,
	CONTROL_REQUEST_SET_SHORT_REGISTER,
	CONTROL_REQUEST_GET_LONG_REGISTER,
	CONTROL_REQUEST_SET_LONG_REGISTER,
	CONTROL_REQUEST_BEEP,
};

#endif

