	; asmsyntax=pic
	radix dec
	processor 18F4550
#include <p18f4550.inc>

	config PLLDIV=1, FOSC=INTOSC_EC, FCMEN=OFF, IESO=OFF
	config PWRT=ON, BOR=OFF, VREGEN=OFF, WDT=OFF, MCLRE=ON, PBADEN=OFF, CCP2MX=ON
	config STVREN=ON, LVP=OFF, ICPRT=OFF, XINST=ON, DEBUG=OFF
	config CP0=OFF, CP1=OFF, CP2=OFF, CP3=OFF, CPB=OFF, CPD=OFF
	config WRT0=OFF, WRT1=OFF, WRT2=OFF, WRT3=OFF, WRTB=OFF, WRTC=OFF, WRTD=OFF
	config EBTR0=OFF, EBTR1=OFF, EBTR2=OFF, EBTR3=OFF, EBTRB=OFF

	end
