#ifndef SHARED_PIPES_H
#define SHARED_PIPES_H

#include <stdint.h>

#define PIPE_DRIVE 0
#define PIPE_FEEDBACK 1
#define PIPE_KICK 2
#define PIPE_FIRMWARE_OUT 3
#define PIPE_FIRMWARE_IN 4
#define PIPE_TEST_MODE 5
#define PIPE_AUTOKICK_INDICATOR 6
#define PIPE_EXPERIMENT_DATA 6
#define PIPE_MAX 6

#define PIPE_OUT_MASK ((1 << PIPE_DRIVE) | (1 << PIPE_KICK) | (1 << PIPE_FIRMWARE_OUT) | (1 << PIPE_TEST_MODE))
#define PIPE_IN_MASK ((1 << PIPE_FEEDBACK) | (1 << PIPE_FIRMWARE_IN) | (1 << PIPE_EXPERIMENT_DATA))

#define PIPE_STATE_TRANSPORT_MASK ((1 << PIPE_DRIVE) | (1 << PIPE_FEEDBACK))
#define PIPE_MESSAGE_MASK ((1 << PIPE_KICK) | (1 << PIPE_FIRMWARE_OUT) | (1 << PIPE_FIRMWARE_IN) | (1 << PIPE_TEST_MODE) | (1 << PIPE_EXPERIMENT_DATA))

#endif

